### ISSUE TITLE
code error in book

### ISSUE THREAD

**Issue by dev2007** [michaelgearon/Tiny-CSS-Projects#5]
![image](https://github.com/michaelgearon/Tiny-CSS-Projects/assets/2928298/c3b6f662-264c-42b5-b018-7b81fb46b5e2)

In Chapter 5,Listing 5.8,the code shows as the image,but the correct code is:

```css
background:  url("bg-img.jpg");
```

**Comment by michaelgearon** [comment]
Hi @dev2007, thanks for the comment, this will be submitted for correction. I hope you're enjoying the book! Mike
